# Generated by Django 5.0.6 on 2024-07-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=5000)),
                ('answer', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
