# Generated by Django 5.0.6 on 2024-07-07 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Models', '0003_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='App_Models.subcategory'),
            preserve_default=False,
        ),
    ]
