# Generated by Django 5.0.6 on 2024-08-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Models', '0004_content_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombaseuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Student', 'Student'), ('Conten', 'Content')], default='Student', max_length=30),
        ),
    ]
