# Generated by Django 5.0.6 on 2024-08-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Models', '0005_alter_custombaseuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombaseuser',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Admin', 'Admin'), ('Conten', 'Content')], default='Student', max_length=30),
        ),
    ]
