# Generated by Django 5.0.6 on 2024-08-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Models', '0008_rename_correct_option_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombaseuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='custombaseuser',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
