# Generated by Django 5.0.6 on 2024-08-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Models', '0009_custombaseuser_otp_custombaseuser_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombaseuser',
            name='is_otp_verify',
            field=models.BooleanField(default=False),
        ),
    ]
